name: Oppdater flom-projeksjon

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: write   

jobs:
  update-flom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: "Debug: list files in workspace"
        run: |
          echo "Working directory: $PWD"
          find . -maxdepth 4 | sed 's/^/   /'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn requests csvtojson

      - name: Run flood script
        run: python optinnbachelor/Scripts/AI.py
        env:
          FROST_CLIENT_ID:     ${{ secrets.FROST_CLIENT_ID }}
          FROST_CLIENT_SECRET: ${{ secrets.FROST_CLIENT_SECRET }}
          NVE_API_KEY:         ${{ secrets.NVE_API_KEY }}

      - name: Commit & push CSV
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add optinnbachelor/data/latest_projisert_flom.csv
          git diff --quiet || git commit -m "Automatisk oppdatering av flom-data"
          git push