# .github/workflows/update-flom.yml
name: Oppdater flom-projeksjon

# Kjøre hver dag kl 02:00 UTC, og også manuelt via "Run workflow"
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update-flom:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      
      - name: Installer Python-avhengigheter
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn requests csvtojson

     
      - name: Kjør flom-skriptet
        run: |
          cd /optinnbachelor/scripts
          python AI.py
        env:
          FROST_CLIENT_ID: ${{ secrets.FROST_CLIENT_ID }}
          FROST_CLIENT_SECRET: ${{ secrets.FROST_CLIENT_SECRET }}
          NVE_API_KEY: ${{ secrets.NVE_API_KEY }}

      
      - name: Commit & push oppdatert CSV
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add optinnbachelor/data/latest_projisert_flom.csv
          # Hvis det ikke er noen endringer, hopper vi over commit/push
          git diff --cached --quiet || git commit -m "Automatisk oppdatering av flom-data"
          git push
